### ISSUE TITLE
Class 'FCrawling\FCrawling' not found

### ISSUE THREAD

**Issue by khushboo2904** [Sahil-Gulati/MREmail#1]
Hello Sahil,

I am getting this below error when i am using ur library. Where do i get this F Crawling Library. 
Fatal error: Class 'FCrawling\FCrawling' not found in.

**Comment by khushboo2904** [comment]
get it from ur another library https://github.com/Sahil-Gulati/FCrawling. 
Thankx

**Comment by Sahil-Gulati** [comment]
Hi Khushboo,

Thanks for reaching me. The reason behind this `fatal error` is that one of the library classes are not present which are expected to be. This library is dependent on few library'es `FCrawling` is one of them. To prevent getting such error make to install it via composer. As described in this section [Installation](https://github.com/Sahil-Gulati/MREmail#installation)
