### ISSUE TITLE
Fatal error: Call to undefined function callback_function()

### ISSUE THREAD

**Issue by khushboo2904** [Sahil-Gulati/MREmail#2]
Hello Sahil,
I am getting this error. I already create a callback_function() in my controller. i am working on zf2. please reply asap.

Fatal error: Call to undefined function callback_function() in

**Comment by Sahil-Gulati** [comment]
Hi Khushboo,

Thanks for reaching me, I will surely help you out. I have checked my library it is working fine.

**Possible Reasons of this error:**

>1. You haven't defined that function.

>2. You haven't defined function as global.

>3. Or you are using it in some different way.

For Reference you can check library's usage pattern for callback.
/**
 * Callback function type
 * (String) `callback_function` global function
 * (Array) array => 0 (Object) `$classObject` array => 1 (String) `function_name`(public) 
 * (Array) array => 0 (String) `class_name` array => 1 (String) `function_name`(public static) 
 */
You can see its usage here https://github.com/Sahil-Gulati/MREmail#usage 

**Note:**
>1. Make sure if you are copying `usage section`'s php code  for some initial testing, don't forget to copy that function  `callback_function` which is defined in the bottom of `usage` section.
>2. You can also try this example from the source of this current library, [Example](https://github.com/Sahil-Gulati/MREmail/blob/master/src/MREmail/Example.php), Try complete example.



If still above doesn't solve your problem. You can share your code which you are using on my personal email address sahil.gulati1991@outlook.com. I will be happy to help you out.

Thanks and Regards,
Sahil Gulati
