### ISSUE TITLE
Update to Signature V4

### ISSUE THREAD

**Issue by CheapCharts** [Sahil-Gulati/MREmail#4]
Hey! Any plans to update your great lib to Amazon Signature V4? They are sending mails that they shut down V3 (what MREmail is using right now) on Oct 1.

References: 
https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html
https://docs.aws.amazon.com/ses/latest/DeveloperGuide/using-ses-api-authentication.html

**Comment by Sahil-Gulati** [comment]
@LuMpeH We are almost done with the development. Hope you will get notification soon when we migrate to AWS signature V4.

**Comment by Sahil-Gulati** [comment]
@LuMpeH Library [MREmail 2.0.0](https://github.com/Sahil-Gulati/MREmail) is now available with AWSV4 signature. You can download it `composer require sahil-gulati/mr-email:2.0.0`.

There is a 
1.  Change in a parameter `region` of SESEmail class.
2.  Addition of `setContentType` function which adds `Accept` header while signing request to AWS.

**Comment by CheapCharts** [comment]
This is fantastic, thanks so much! Will try it very soon.
